version: 0.2

phases:
  install:
    commands:
      - npm -g install eslint

  pre_build:
    commands:
      - npm run lint

  build:
    commands:
      - npm run build:android

artifacts:
  type: zip
  files: 
    - test.zip