version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm -g install eslint

  pre_build:
    commands:
      - npm run lint

  build:
    commands:
      - npm run build:android

artifacts:
  type: zip
  files:
    - "android/app/build/outputs/bundle/**/*"
